"""Whole-corpus label and size statistics per stored tier, and the LaTeX table built from them.

The companion of ``corpus_stats.py``: that one describes the 55 *source designs*, this one
describes the ~1.15M *graphs* the transformation and labelling produce
(\\ref{sec:method:data:tiers}).

Reads the per-algorithm ML CSV written by ``shell/10_algorithm_csv.sh``. Two things about
that file matter and are easy to get wrong:

* Its ``tier_id`` is the tier of the *labelling run*, not of the sample. A ``tier_id=1`` row
  is a tier-0 graph labelled by its tier-1 synthesis run; a ``tier_id=2`` row is a tier-1
  graph labelled by its tier-2 run. The thesis names tiers after the sample, so the mapping
  is ``sample tier = tier_id - 1``.
* The ``pre_*`` columns describe the input (unoptimized) graph, i.e. the sample. Node count
  is ``1 + pre_num_PI + pre_nodes + pre_num_PO`` (constant + PIs + ANDs + POs), the same
  identity ``src/data/dataset.py`` uses to size graphs without loading them.

Step 21 of every recipe is ``dch``, which builds a choice network: abc reports the AND count
of the representative structure while ``write_aiger`` also emits the choice nodes, so
``pre_nodes`` understates those graphs. They are excluded from the size statistics and
counted in the footnote rather than silently averaged in.

Usage (on the cluster, where the CSVs live)::

    python data/creation/corpus_tier_stats.py
    python data/creation/corpus_tier_stats.py --latex > \\
        IV_Gardner___Master_AI_Thesis_Outline/media/tables/corpus_tiers.tex
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import pandas as pd

DEFAULT_CSV = Path("data/designs/design_metadata/algo_Orchestrate_ml.csv")

# Position 21 of every reference recipe is `dch`; see the module docstring.
UNTRUSTED_STEP = "21"

SOURCE_RE = re.compile(r"/tier1/([^/]+)/")


def load(csv_path: Path) -> pd.DataFrame:
    df = pd.read_csv(csv_path)
    for col in ("pre_nodes", "pre_num_PI", "pre_num_PO", "optimizability", "tier_id"):
        df[col] = pd.to_numeric(df[col], errors="coerce")

    df = df.dropna(subset=["optimizability", "tier_id"])
    df["sample_tier"] = df["tier_id"].astype(int) - 1
    df["num_nodes"] = 1 + df["pre_num_PI"] + df["pre_nodes"] + df["pre_num_PO"]
    df["trusted_size"] = df["step_id"].astype(str).str.strip() != UNTRUSTED_STEP
    # A tier-1 sample's source script is the directory its graph sits in.
    df["source"] = df["unoptimized_graph_path"].str.extract(SOURCE_RE, expand=False)
    return df


def summarise(df: pd.DataFrame, label: str) -> dict:
    sized = df[df["trusted_size"]]
    y = df["optimizability"]
    return {
        "Group": label,
        "Graphs": len(df),
        "Median nodes": int(sized["num_nodes"].median()) if len(sized) else 0,
        "Max nodes": int(sized["num_nodes"].max()) if len(sized) else 0,
        "Mean $y$": round(float(y.mean()), 4),
        "SD $y$": round(float(y.std()), 4),
        "$y = 0$": round(float((y == 0).mean()), 3),
        "$y < 0.005$": round(float((y < 0.005).mean()), 3),
    }


def build_rows(df: pd.DataFrame) -> pd.DataFrame:
    rows = [
        summarise(df[df["sample_tier"] == 0], "Tier 0 (base graphs)"),
        summarise(df[df["sample_tier"] == 1], "Tier 1 (single-algorithm)"),
    ]
    tier1 = df[df["sample_tier"] == 1]
    for source in sorted(tier1["source"].dropna().unique()):
        rows.append(summarise(tier1[tier1["source"] == source], f"\\quad from {source}"))
    rows.append(summarise(df, "Pooled"))
    return pd.DataFrame(rows)


def to_latex(rows: pd.DataFrame, n_untrusted: int, n_total: int) -> str:
    header = " & ".join(f"\\textbf{{{c}}}" for c in rows.columns) + r" \\"
    body = []
    for _, r in rows.iterrows():
        cells = [str(r["Group"])] + [f"{r[c]:,}" if isinstance(r[c], int) else f"{r[c]}"
                                     for c in rows.columns[1:]]
        body.append(" & ".join(cells) + r" \\")
    share = 100.0 * n_untrusted / n_total if n_total else 0.0
    return "\n".join([
        "% Generated by data/creation/corpus_tier_stats.py --latex. Do not edit by hand.",
        r"\begin{table*}[htbp]",
        r"\centering",
        r"\caption[Whole-corpus statistics by tier]{Label and size statistics over the whole "
        r"corpus, per stored tier and by the synthesis script that produced each tier-1 "
        r"graph. Node counts are constant $+$ primary inputs $+$ AND nodes $+$ primary "
        r"outputs of the unoptimized graph.}",
        r"\label{tab:corpus_stats}",
        r"\small",
        r"\resizebox{\textwidth}{!}{%",
        r"\begin{tabular}{l" + "r" * (len(rows.columns) - 1) + "}",
        r"\toprule",
        header,
        r"\midrule",
        *body,
        r"\bottomrule",
        r"\end{tabular}",
        "}",
        r"\\[4pt]\begin{minipage}{\linewidth}\footnotesize\emph{Size statistics exclude the "
        f"{n_untrusted:,} step-21 graphs ({share:.1f}\\% of the corpus), whose reported node "
        r"count understates the written AIG: step 21 of every recipe is \texttt{dch}, which "
        r"builds a choice network. Label statistics cover every graph.}\end{minipage}",
        r"\end{table*}",
    ])


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--csv", type=Path, default=DEFAULT_CSV)
    parser.add_argument("--latex", action="store_true", help="emit the LaTeX table on stdout")
    args = parser.parse_args()

    if not args.csv.exists():
        sys.exit(
            f"ERROR: {args.csv} not found.\n"
            "This runs on the cluster, where shell/10_algorithm_csv.sh writes the ML CSVs."
        )

    df = load(args.csv)
    rows = build_rows(df)
    n_untrusted = int((~df["trusted_size"]).sum())

    if args.latex:
        print(to_latex(rows, n_untrusted, len(df)))
    else:
        print(rows.to_string(index=False))
        print(f"\n{n_untrusted:,} of {len(df):,} rows excluded from size statistics (step 21).")


if __name__ == "__main__":
    main()
